In [2]:
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest

In [3]:
df = pd.read_csv('Sample scores.csv')
df

    Overs  Scores
0       1      15
1       2      10
2       3      17
3       4      10
4       5      12
5       6      20
6       7     100
7       8       7
8       9       8
9      10      11
10     11     100
11     12      14
12     13       3
13     14     100
14     15      11
15     16      13
16     17     100
17     18      16
18     19      26
19     20      30

In [4]:
model=IsolationForest(n_estimators=1000,max_samples='auto',contamination=float(0.2),max_features=1.0)
model.fit(df[['Scores']])

IsolationForest(contamination=0.2, n_estimators=1000)

In [5]:
df['scores']=model.decision_function(df[['Scores']])
df['anomaly']=model.predict(df[['Scores']])
df.head(20)

    Overs  Scores    scores  anomaly
0       1      15  0.217062        1
1       2      10  0.238335        1
2       3      17  0.182980        1
3       4      10  0.238335        1
4       5      12  0.234626        1
5       6      20  0.109175        1
6       7     100 -0.021292       -1
7       8       7  0.144497        1
8       9       8  0.177666        1
9      10      11  0.248936        1
10     11     100 -0.021292       -1
11     12      14  0.223662        1
12     13       3  0.005323        1
13     14     100 -0.021292       -1
14     15      11  0.248936        1
15     16      13  0.229416        1
16     17     100 -0.021292       -1
17     18      16  0.206693        1
18     19      26  0.058269        1
19     20      30  0.008441        1

In [6]:
outliers_counter = len(df[df['Scores'] > 36])
outliers_counter

4